json.id plant.id
json.name plant.name
json.species plant.species
json.plant_image plant.plant_image
json.sun_amount plant.sun_amount
json.days_water plant.days_water
json.description plant.description
json.created_at plant.created_at
json.updated_at plant.updated_at